---
title: 'Socially Vulnerable Populations and Susceptibility to Damages'
subtitle: 'Census Tract Aggregation Pre-Analysis'
author: 'Ross MacLean'
geometry: margin=1in
output:
  github_document: default
  pdf_document: default
  toc: yes
  number_sections: yes
fontsize: 11pt
knit: (function(inputFile, encoding) {
  rmarkdown::render(
    inputFile, encoding = encoding,
    output_format = c('github_document', 'pdf_document'))
    })
---

```{r}
# Load packages
library(car)
library(dplyr)
library(data.table)
library(ggplot2)
library(gridExtra)
library(GGally)
library(knitr)
library(corrplot)
library(lmtest)
library(sandwich)
library(stargazer)

options(scipen=999)
```

# Explortory Data Analysis

```{r}
# Read in PR data
d <- fread(file = '../data/open-fema/FEMA-Large-Tract-Demographics-WindSpeed-PR.csv', encoding = 'UTF-8')
```

## FEMA Distrbutions

```{r, fig.width=10, fig.height=3.5, warning=FALSE}
# Damage amount
p_damage <- ggplot(d, aes(damageamount_cap)) +
  geom_histogram(bins = 30, fill = '#F8766D', color = '#F6493c') +
  xlab('Damage amount') + ylab('Frequency') +
  ggtitle('Damage Amount per Captia')

# Damage amount log
p_damage_log <- ggplot(d, aes(log(damageamount_cap))) +
  geom_histogram(bins = 30, fill = '#00BFC4', color = '#00998C') +
  xlab('Log damage amount') + ylab('Frequency') +
  ggtitle('Log of Damage Amount per Captia')

grid.arrange(p_damage, p_damage_log, ncol=2)
```

```{r, fig.width=10, fig.height=3.5, warning=FALSE}
# Wind speed
p_wind <- ggplot(d, aes(pwg_mph)) +
  geom_histogram(bins = 30, fill = '#F8766D', color = '#F6493c') +
  xlab('Peak wind gust') + ylab('Frequency') +
  ggtitle('Peak Wind Gust')

# Wind speed log
p_wind_log <- ggplot(d, aes(log(pwg_mph))) +
  geom_histogram(bins = 30, fill = '#00BFC4', color = '#00998C') +
  xlab('Log peak wind gust') + ylab('Frequency') +
  ggtitle('Log of Peak Wind Gust')

grid.arrange(p_wind, p_wind_log, ncol=2)
```

```{r, fig.width=10, fig.height=3.5, warning=FALSE}
# Waterlevel
p_water <- ggplot(d, aes(waterlevel)) +
  geom_histogram(bins = 30, fill = '#F8766D', color = '#F6493c') +
    xlab('Water-level') + ylab('Frequency') +
    ggtitle('Water-Level')

# Waterlevel log
p_wind_log <- ggplot(d, aes(log(waterlevel))) +
  geom_histogram(bins = 30, fill = '#00BFC4', color = '#00998C') +
    xlab('Log of water-level') + ylab('Frequency') +
    ggtitle('Log of Water-Level')

grid.arrange(p_water, p_wind_log, ncol=2)
```

## Demographic Distrbutions

```{r, fig.width=10, fig.height=3.5, warning=FALSE}
# Poverty
p_poverty <- ggplot(d, aes(below_poverty_rate)) +
  geom_histogram(bins = 30, fill = '#F8766D', color = '#F6493c') +
  xlab('Poverty rate') + ylab('Frequency') +
  ggtitle('Poverty Rate')

# Poverty log
p_poverty_log <- ggplot(d, aes(log(below_poverty_rate))) +
  geom_histogram(bins = 30, fill = '#00BFC4', color = '#00998C') +
  xlab('Log poverty rate') + ylab('Frequency') +
  ggtitle('Log of Poverty Rate')

grid.arrange(p_poverty, p_poverty_log, ncol=2)
```

```{r, fig.width=10, fig.height=3.5, warning=FALSE}
# Unemployment
p_unemploy <- ggplot(d, aes(unemployed_labor_rate)) +
  geom_histogram(bins = 30, fill = '#F8766D', color = '#F6493c') +
  xlab('Unemployment rate') + ylab('Frequency') +
  ggtitle('Unemployment Rate')

# Unemployment log
p_unemploy_log <- ggplot(d, aes(log(unemployed_labor_rate))) +
  geom_histogram(bins = 30, fill = '#00BFC4', color = '#00998C') +
  xlab('Log unemployment rate') + ylab('Frequency') +
  ggtitle('Log of Unemployment Rate')

grid.arrange(p_unemploy, p_unemploy_log, ncol=2)
```

```{r, fig.width=10, fig.height=3.5, warning=FALSE}
# Bachelors Degree
p_bachelors_deg <- ggplot(d, aes(bachelors_degree_rate)) +
  geom_histogram(bins = 30, fill = '#F8766D', color = '#F6493c') +
  xlab('Bachelors Degree') + ylab('Frequency') +
  ggtitle('Bachelors Degree')

# Median earnings log
p_bachelors_deg_log <- ggplot(d, aes(log(bachelors_degree_rate))) +
  geom_histogram(bins = 30, fill = '#00BFC4', color = '#00998C') +
  xlab('Log Bachelors Degree') + ylab('Frequency') +
  ggtitle('Log of Bachelors Degree')

grid.arrange(p_bachelors_deg, p_bachelors_deg_log, ncol=2)
```


```{r, fig.width=10, fig.height=3.5, warning=FALSE}
# Median earnings
p_earnings <- ggplot(d, aes(median_earnings_total)) +
  geom_histogram(bins = 30, fill = '#F8766D', color = '#F6493c') +
  xlab('Median earnings') + ylab('Frequency') +
  ggtitle('Median Earnings')

# Median earnings log
p_earnings_log <- ggplot(d, aes(log(median_earnings_total))) +
  geom_histogram(bins = 30, fill = '#00BFC4', color = '#00998C') +
  xlab('Log median earnings') + ylab('Frequency') +
  ggtitle('Log of Median Earnings')

grid.arrange(p_earnings, p_earnings_log, ncol=2)
```

```{r, fig.width=10, fig.height=3.5, warning=FALSE}
# Built year
p_built <- ggplot(d, aes(built_1979_or_earlier_rate)) +
  geom_histogram(bins = 30, fill = '#F8766D', color = '#F6493c') +
  xlab('Built pre-1979') + ylab('Frequency') +
  ggtitle('House Built Pre-1979')

# Built year log
p_built_log <- ggplot(d, aes(log(built_1979_or_earlier_rate))) +
  geom_histogram(bins = 30, fill = '#00BFC4', color = '#00998C') +
  xlab('Log built pre-1979') + ylab('Frequency') +
  ggtitle('Log of House Built Pre-1979')

grid.arrange(p_built, p_built_log, ncol=2)
```

```{r, fig.width=10, fig.height=3.5, warning=FALSE}
# Ownership
p_owner <- ggplot(d, aes(owner_occupied_rate)) +
  geom_histogram(bins = 30, fill = '#F8766D', color = '#F6493c') +
  xlab('Ownership rate') + ylab('Frequency') +
  ggtitle('Ownership Rate')

# Ownership log
p_owner_log <- ggplot(d, aes(log(owner_occupied_rate))) +
  geom_histogram(bins = 30, fill = '#00BFC4', color = '#00998C') +
  xlab('Log ownership rate') + ylab('Frequency') +
  ggtitle('Log of Ownership Rate')

grid.arrange(p_owner, p_owner_log, ncol=2)
```

## SVI Distributions

```{r, fig.width=10, fig.height=3.5, warning=FALSE}
# Missing SVIs
#d[svi_total == -999, c('censustractid', 'svi_socioeconomic', 'svi_householdcomp', 'svi_minority', 'svi_housingtype', 'svi_total')]

# SVI
p_svi <- d %>%
  dplyr::filter('svi_total' != -999) %>%
  ggplot(aes(svi_total)) +
    geom_histogram(bins = 30, fill = '#F8766D', color = '#F6493c') +
    xlab('SVI') + ylab('Frequency') +
    ggtitle('SVI')

# SVI log
p_svi_log <- d %>%
  dplyr::filter('svi_total' != -999) %>%
  ggplot(aes(log(svi_total))) +
    geom_histogram(bins = 30, fill = '#00BFC4', color = '#00998C') +
    xlab('Log of SVI') + ylab('Frequency') +
    ggtitle('Log of SVI')

grid.arrange(p_svi, p_svi_log, ncol=2)
```

## Damage Amount per capita by County

```{r fig.height=5, fig.width=9}
ggplot(d, aes(as.factor(county_fips), damageamount_cap)) + geom_boxplot(aes(fill = as.factor(county_fips))) +  geom_jitter(width = 0.2, size = 0.5) + 
ggtitle("Damage Amount per capita by county") + theme(plot.title = element_text(lineheight = 1, face = "bold")) + theme(legend.position="right", legend.text=element_text(size=5), axis.text.x = element_text(angle = -90, vjust = 0.5, size = 5, face = "plain"))
```


## Correlations Matrix

```{r}
cor_matrix <- round(cor(d[,c('damageamount_cap', 'pwg_mph', 'waterlevel', 'below_poverty_rate', 'unemployed_labor_rate', 'bachelors_degree_rate', 'built_1979_or_earlier_rate', 'owner_occupied_rate')], use='complete.obs'), 2)
corrplot(cor_matrix, method="square")
```


## Bivariate Analysis (damageamount_cap and explanatory variables)

```{r fig.height=8, fig.width=10}
plot_bivariate <- function(var, var.name) {
  p.plot <- ggplot(d, aes(x=var, y=damageamount_cap)) + geom_point(size=2, shape=18, color="lightblue", na.rm = TRUE) + 
    xlab(var.name) + theme(plot.title = element_text(lineheight = 1, face = "bold"))
}
grid.arrange(plot_bivariate(d$pwg_mph, "pwg_mph"),
             plot_bivariate(d$pwg_saffir_simpson, "pwg_saffir_simpson"),
             plot_bivariate(d$waterlevel, "waterlevel"),
             plot_bivariate(d$below_poverty_rate, "below_poverty_rate"),
             plot_bivariate(d$median_earnings_total, "median_earings_total"),
             plot_bivariate(d$bachelors_degree_rate, "bachelors_degree_rate"),
             plot_bivariate(d$unemployed_labor_rate, "unemployed_labor_rate"),
             plot_bivariate(d$built_1979_or_earlier_rate, "built_1979_or_earlier_rate"),
             plot_bivariate(d$owner_occupied_rate, "owner_occupied_rate"), 
             plot_bivariate(d$svi_socioeconomic, "svi_socioeconomic"),
             plot_bivariate(d$svi_householdcomp, "svi_socioeconomic"),
             plot_bivariate(d$svi_minority, "svi_minority"),
             plot_bivariate(d$svi_housingtype, "svi_housingtype"),
             plot_bivariate(d$svi_total, "svi_total"), nrow=4)
```

## Bivariate Analysis (log(damageamount_cap) and explanatory variables)

```{r fig.height=8, fig.width=10}
plot_bivariate <- function(var, var.name) {
  p.plot <- ggplot(d, aes(x=var, y=log(damageamount_cap))) + geom_point(size=2, shape=18, color="lightblue", na.rm = TRUE) + 
    xlab(var.name) + theme(plot.title = element_text(lineheight = 1, face = "bold"))
}
grid.arrange(plot_bivariate(d$pwg_mph, "pwg_mph"),
             plot_bivariate(d$pwg_saffir_simpson, "pwg_saffir_simpson"),
             plot_bivariate(log(d$waterlevel), "waterlevel"),
             plot_bivariate(d$below_poverty_rate, "below_poverty_rate"),
             plot_bivariate(d$median_earnings_total, "median_earings_total"),
             plot_bivariate(d$bachelors_degree_rate, "bachelors_degree_rate"),
             plot_bivariate(d$unemployed_labor_rate, "unemployed_labor_rate"),
             plot_bivariate(d$built_1979_or_earlier_rate, "built_1979_or_earlier_rate"),
             plot_bivariate(d$owner_occupied_rate, "owner_occupied_rate"), 
             plot_bivariate(d$svi_socioeconomic, "svi_socioeconomic"),
             plot_bivariate(d$svi_householdcomp, "svi_socioeconomic"),
             plot_bivariate(d$svi_minority, "svi_minority"),
             plot_bivariate(d$svi_housingtype, "svi_housingtype"),
             plot_bivariate(d$svi_total, "svi_total"), nrow=3)
```


```{r}
model1 <- lm(formula=log1p(damageamount_cap) ~ pwg_mph + log1p(waterlevel) + below_poverty_rate + bachelors_degree_rate + unemployed_labor_rate + built_1979_or_earlier_rate + owner_occupied_rate, data = d)

summary(model1)
par(mfrow=c(2,2), mar=c(4.0,4.1,2.1,1.1))
plot(model1)
bptest(model1)
vif(model1)
coeftest(model1, vcov = vcovHC(model1), type='HC3')
coeftest(model1, vcov = vcovCL(model1, cluster = d$county_fips))
```


```{r , results = 'asis'}
stargazer(model1, model1,
          type = "latex",
          no.space = TRUE,
          font.size = "small",
          title = "Social Vulnerability and Susceptibility to Damages",
          covariate.labels = c("Peak Wind Gusts (mph)", "Water Level (log)","Below Poverty Rate", "Unemployed Labor Rate", "Homes built 1979 or Earlier Rate", "Owner Occupied Rate"),
          dep.var.labels = "Per Capita Damage Amount (Log)",
          se = c(list(sqrt(diag(vcovHC(model1, type="HC3")))), list(sqrt(diag(vcovCL(model1, cluster=d$county_fips))))),
          add.lines = list(c("SE Type", "Robust", "Clustered")), 
          header = F)
```

### peak wind gust saffir simpson scale
```{r}
model2 <- lm(formula=log1p(damageamount_cap) ~ pwg_saffir_simpson + log1p(waterlevel) + below_poverty_rate + bachelors_degree_rate + unemployed_labor_rate + built_1979_or_earlier_rate + owner_occupied_rate, data = d)

summary(model2)
par(mfrow=c(2,2), mar=c(4.0,4.1,2.1,1.1))
plot(model2)
bptest(model2)
vif(model2)
coeftest(model2, vcov = vcovHC(model2), type='HC3')

```

### Fixed Effects
```{r}
model3 <- lm(formula=log1p(damageamount_cap) ~ pwg_mph + log1p(waterlevel) + factor(county), data = d)

summary(model3)
par(mfrow=c(2,2), mar=c(4.0,4.1,2.1,1.1))
plot(model3)
bptest(model3)
vif(model3)
```
