---
title: 'Census County Demographics'
subtitle: 'Census Demographic Master Script'
author: 'Ross MacLean'
geometry: margin=1in
output:
  github_document: default
  pdf_document: default
  toc: yes
  number_sections: yes
fontsize: 11pt
knit: (function(inputFile, encoding) {
  rmarkdown::render(
    inputFile, encoding = encoding,
    output_format = c('github_document', 'pdf_document'))
    })
---

```{r}
# Load packages
library(car)
library(dplyr)
library(tidyr)
library(data.table)
library(ggplot2)
library(ggcorrplot)
library(gridExtra)
library(GGally)
library(knitr)
```

# Combine Individual Census Files

```{r}
# Column names
fact <- c("pop_estimates_2019",
          "pop_estimates_2010",
          "pop_percent_change",
          "pop_census_2010",
          "pop_under_5yrs_percent",
          "pop_under_18yrs_percent",
          "pop_65yrs_over_percent",
          "female_percent",
          "white_alone_percent",
          "black_alone_percent",
          "american_indian_alaska_native_alone_percent",
          "asian_alone_percent",
          "pacific_islander_alone_percent",
          "two_or_more_races_percent",
          "hispanic_percent",
          "white_alone_not_hispanic_percent",
          "veterans",
          "foreign_born_persons_percent",
          "housing_units",
          "owner_occupied_housing_rate",
          "median_value_of_owner_occupied_house",
          "median_monthly_owner_costs_mortgage",
          "median_monthly_owner_cost_no_mortgage",
          "median_gross_rent",
          "building_permits",
          "households",
          "persons_per_household",
          "living_house_year_ago_percent_aged_1yr_over",
          "language_non_english_percent_aged_5yrs",
          "households_computer_percent",
          "households_broadband_percent",
          "high_school_graduate_percent_25yrs_over",
          "bachelors_degree_percent_25yrs_over",
          "disabled_under_65yrs_percent",
          "no_health_insurance_under_65yrs_percent",
          "labor_total_percent_age_16yrs",
          "labor_force_female_percent_age_16yrs",
          "accommodation_food_services_sales",
          "health_care_and_social_revenue",
          "manufacturers_shipments",
          "merchant_wholesaler_sales",
          "retail_sales",
          "retail_sales_per_capita",
          "mean_travel_time_to_work_mins",
          "median_household_income",
          "per_capita_income_past_year",
          "poverty_percent",
          "employer_establishments",
          "employment",
          "annual_payroll",
          "employment_percent_change",
          "nonemployer_establishments",
          "all_firms",
          "male_owned_firms",
          "female_owned_firms",
          "minority_owned_firms",
          "nonminority_owned_firms",
          "veteran_owned_firms",
          "nonveteran_owned_firms",
          "pop_per_square_mile",
          "land_area_square_miles",
          "fips_code")
```

```{r}
# Function which read in county data and cleans the file for stacking
tidy_data <- function(file, county){
  
  # Read data
  d <- fread(file = file, encoding = 'UTF-8')
  
  # Select required columns
  d <- d[ ,c(1,3)]
  (county_name <- names(d[, 2]))
  fact_desc <- d$Fact
  
  # Create long dataset
  d_county <- data.table(county = rep(county_name, length(fact)),
             fact = fact)
  
  names(d) <- c('fact', 'value')
  
  # Select rows
  n <- length(fact)
  values <- d[1:n, value]
  
  d_county <- cbind(d_county, value = values)
  return(d_county)
}
```


```{r}
# Identify all census files
filenames <- list.files("../data/census-county/raw/", pattern="*.csv", full.names=TRUE)

d_full <- tidy_data(filenames[1])

# Loop through all files except first
for (file in tail(filenames, -1)) {
  
  # Read data and stack
  d_county <- tidy_data(file = file)
  d_full <- rbind(d_full, d_county)
}

# Reshape to wide
d_wide <- reshape(d_full, idvar = "county", timevar = "fact", direction = "wide")

# Clean up variable names
names(d_wide) <- c('county', fact)

# Reorder columns
d_wide <- d_wide %>%
  select(fips_code, everything())

head(d_wide)
```

# Reformat Variables

```{r}
# Replace redacted values with NA
d_wide[d_wide == 'X'] <- NA
d_wide[d_wide == 'D'] <- NA
d_wide[d_wide == 'NA'] <- NA

# Convery fips code
d_wide[ , `:=` (county = gsub(', Puerto Rico', '', county))]

# Convery fips code
d_wide[ , `:=` (fips_code = as.numeric(gsub('"', '', fips_code)))]

# Convert number characters to integers (no commas)
d_wide[ , `:=` (pop_estimates_2019 = as.numeric(gsub(',', '', pop_estimates_2019)),
                pop_estimates_2010 = as.numeric(gsub(',', '', pop_estimates_2010)),
                pop_census_2010 = as.numeric(gsub(',', '', pop_estimates_2010)),
                veterans = as.numeric(gsub(',', '', veterans)),
                housing_units = as.numeric(gsub(',', '', housing_units)),
                building_permits = as.numeric(gsub(',', '', building_permits)),
                households = as.numeric(gsub(',', '', households)),     
                accommodation_food_services_sales = as.numeric(gsub(',', '', accommodation_food_services_sales)),
                health_care_and_social_revenue = as.numeric(gsub(',', '', health_care_and_social_revenue)),
                manufacturers_shipments = as.numeric(gsub(',', '', manufacturers_shipments)),
                merchant_wholesaler_sales = as.numeric(gsub(',', '', merchant_wholesaler_sales)),
                retail_sales = as.numeric(gsub(',', '', retail_sales)),
                employer_establishments = as.numeric(gsub(',', '', employer_establishments)),
                employment = as.numeric(gsub(',', '', employment)),
                annual_payroll = as.numeric(gsub(',', '', annual_payroll)),
                nonemployer_establishments = as.numeric(gsub(',', '', nonemployer_establishments)),
                all_firms = as.numeric(gsub(',', '', all_firms)),
                male_owned_firms = as.numeric(gsub(',', '', male_owned_firms)),
                female_owned_firms = as.numeric(gsub(',', '', female_owned_firms)),
                minority_owned_firms = as.numeric(gsub(',', '', minority_owned_firms)),
                nonminority_owned_firms = as.numeric(gsub(',', '', nonminority_owned_firms)),
                veteran_owned_firms = as.numeric(gsub(',', '', veteran_owned_firms)),
                nonveteran_owned_firms = as.numeric(gsub(',', '', nonveteran_owned_firms)),
                pop_per_square_mile = as.numeric(gsub(',', '', pop_per_square_mile)),
                land_area_square_miles = as.numeric(gsub(',', '', land_area_square_miles)),
                mean_travel_time_to_work_mins = as.numeric(gsub(',', '', mean_travel_time_to_work_mins)))]
```

```{r}
# Convert dollar characters to integers (no dollars/commas)
d_wide[ , `:=` (median_value_of_owner_occupied_house = as.numeric(gsub('[$,]', '', median_value_of_owner_occupied_house)),
                median_monthly_owner_costs_mortgage = as.numeric(gsub('[$,]', '', median_monthly_owner_costs_mortgage)),
                median_monthly_owner_cost_no_mortgage = as.numeric(gsub('[$,-]', '', median_monthly_owner_cost_no_mortgage)),
                median_gross_rent = as.numeric(gsub('[$,]', '', median_gross_rent)),
                retail_sales_per_capita = as.numeric(gsub('[$,]', '', retail_sales_per_capita)),
                median_household_income = as.numeric(gsub('[$,]', '', median_household_income)),
                per_capita_income_past_year = as.numeric(gsub('[$,]', '', per_capita_income_past_year)))]
```


```{r}
# Convert percentage characters to integers
d_wide[ , `:=` (pop_percent_change = as.numeric(gsub('%', '', pop_percent_change))/100,
                pop_under_5yrs_percent = as.numeric(gsub('%', '', pop_under_5yrs_percent))/100,
                pop_under_18yrs_percent = as.numeric(gsub('%', '', pop_under_18yrs_percent))/100,
                pop_65yrs_over_percent = as.numeric(gsub('%', '', pop_65yrs_over_percent))/100,
                female_percent = as.numeric(gsub('%', '', female_percent))/100,
                white_alone_percent = as.numeric(gsub('%', '', white_alone_percent))/100,
                black_alone_percent = as.numeric(gsub('%', '', black_alone_percent))/100,
                american_indian_alaska_native_alone_percent = as.numeric(gsub('%', '', american_indian_alaska_native_alone_percent))/100,
                asian_alone_percent = as.numeric(gsub('%', '', asian_alone_percent))/100,
                pacific_islander_alone_percent = as.numeric(gsub('%', '', pacific_islander_alone_percent))/100,
                two_or_more_races_percent = as.numeric(gsub('%', '', two_or_more_races_percent))/100,
                hispanic_percent = as.numeric(gsub('%', '', hispanic_percent))/100,
                white_alone_not_hispanic_percent = as.numeric(gsub('%', '', white_alone_not_hispanic_percent))/100,
                foreign_born_persons_percent = as.numeric(gsub('%', '', foreign_born_persons_percent))/100,
                owner_occupied_housing_rate = as.numeric(gsub('%', '', owner_occupied_housing_rate))/100,
                living_house_year_ago_percent_aged_1yr_over = as.numeric(gsub('%', '', living_house_year_ago_percent_aged_1yr_over))/100,
                language_non_english_percent_aged_5yrs = as.numeric(gsub('%', '', language_non_english_percent_aged_5yrs))/100,
                households_computer_percent = as.numeric(gsub('%', '', households_computer_percent))/100,
                households_broadband_percent = as.numeric(gsub('%', '', households_broadband_percent))/100,
                high_school_graduate_percent_25yrs_over = as.numeric(gsub('%', '', high_school_graduate_percent_25yrs_over))/100,
                bachelors_degree_percent_25yrs_over = as.numeric(gsub('%', '', bachelors_degree_percent_25yrs_over))/100,
                disabled_under_65yrs_percent = as.numeric(gsub('%', '', disabled_under_65yrs_percent))/100,
                no_health_insurance_under_65yrs_percent = as.numeric(gsub('%', '', no_health_insurance_under_65yrs_percent))/100,
                labor_total_percent_age_16yrs = as.numeric(gsub('%', '', labor_total_percent_age_16yrs))/100,
                labor_force_female_percent_age_16yrs = as.numeric(gsub('%', '', labor_force_female_percent_age_16yrs))/100,
                poverty_percent = as.numeric(gsub('%', '', poverty_percent))/100,
                employment_percent_change = as.numeric(gsub('%', '', employment_percent_change))/100)]

# Write to csv
# fwrite(d_wide, file = '../data/county-demographics.csv')

head(d_wide)
```


# Create FIPS Lookup

```{r}
## Fema counties
# d_fema <- fread(file = '../data/census-county/FEMA-DR-4339-PR.csv')
# county_base <- d_fema[ , .(count = .N), keyby = county]
# fwrite(county_base, file = '../data/census-county/county-fips-lookup.csv')

## Proper county names with fips
# d_pop <- fread(file = '../data/census-county/Puerto Rico Community Survey - Population 5year.csv', skip = 1,
#                       encoding = 'UTF-8')

## Reformat column names
# col_names <- names(d_pop)
# col_names <- gsub('!!', '_', col_names)
# col_names <- gsub(' ', '_', col_names)
# names(d_pop) <- col_names
#
## Convert variables names to lower case
# names(d_pop) <- tolower(names(d_pop))
# 
## Rename variables
# setnames(d_pop, old = c('id', 'geographic_area_name', 'estimate_total_total_population'),
#                  new = c('area_id', 'area_name', 'total_population'))
# 
# d_pop[ , `:=` (fips_code = substr(area_id, 10, 15))]
#
## Keep required fields
# d_pop <- d_pop[ ,c('area_id', 'fips_code', 'area_name', 'total_population')]
# 
# fips_lookup <-  d_pop[ , .(count = .N), keyby = c('area_name', 'fips_code')]

## Write to csv
# fwrite(fips_lookup, file = '../data/census-county/fips_lookup.csv')
```

```{r}
## Above county files combined manually 
# county_lookup <- fread(file = '../data/census-county/county-fips-lookup.csv', encoding = 'UTF-8')
# county_lookup
```






